1. a_tensor_initialization.py 실행결과

a는 크게 3개의 출력부로 나눌 수 있다. 
t1의 dtype,device,requires_grad,size,shape 출력
t2의 dtype,device,requires_grad,size,shape 출력
a1부터 a10까지의 tensor의 shape와 ndim 출력이다. 

In [2]:
import torch

# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

print("#" * 50, 1)



torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1


확인할 점은 Tensor의 dtype이 float32라는 점이다. 아래에서 후술할 tensor와 Tensor는 dtype이 다르다는 점을 확인했다. 

In [3]:
# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

print("#" * 50, 2)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2


tensor의 경우 dtype이 int64이다. 그외엔 [1.2.3]이라는 같은 값을 갖기 때문에 둘은 서로 같다. 

In [4]:

a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

사람마다 같은 개념이라도 이해하는 방식은 조금 다르겠지만 나는 대괄호의 개수에 집중했다. 처음 열리는 대괄호부터 가장 안쪽의 열리는 대괄호까지의 갯수는 ndim과 같다. 
그리고 size는 한 대괄호 안에 들어있는 항목의 갯수이다. 
마지막에 에러가 발생하는데 이는 같은 길이를 가져야할 3차원의 배열들이 다른 길이를 가지기 때문이다. 

2. b_tensor_initialization_copy.py 실행결과

b에서는 6개의 tensor를 출력한다. 이는 [1,2,3]를 값으로 가지는 Tensor, tensor, as_tensor를 출력한 것이다. 

In [5]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


Tensor는 float기 때문에 .이 붙고 tensor와 as_tensor는 붙지 않았다. 
tensor는 ?[0]=100형태의 직접 변환으로 수정되지 않았고, as_tensor는 수정되었다. 

3. c_tensor_initialization_constant_values.py 실행결과

c에서는 4개의 tensor를 출력하는데 이는 3개의 형태를 가진다. 

In [6]:
import torch

t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3)
print(t4)


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0.0000e+00, 0.0000e+00, 1.3189e-33, 6.8944e-43])
tensor([1.4013e-45, 0.0000e+00, 1.3189e-33, 6.8944e-43])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


처음 2개와 그다음 2개는 torch.뒤에 입력한 숫자를 괄호로 입력한 size만큼 포함된 tensor를 출력하는데 정상적으로 출력된다. 
5,6번째 출력은 empty, 빈값의 tensor를 출력했는데 이는 2개가 다른 출력 결과를 보인다.초기화되지 않은 값이 그때그때 출력되기 때문에 다른 값이 출력된 것이다. 
마지막 7번째 출력은 eye로 출력했는데 그 결과 매트릭스 형태로 출력된 것을 확인할 수 있다. 

4. d_tensor_initialization_random_values.py 실행결과

d에서는 10개의 tensor를 출력하였는데 각기 다른 6개의 명령어와 rand를 이용한 4개로 구성된다. 

In [7]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

print("#" * 30)

tensor([[19, 16]])
tensor([[0.7261, 0.5249, 0.9157]])
tensor([[ 0.0470, -2.0531, -0.4094]])
tensor([[ 8.8507, 10.8659],
        [ 9.0490, 10.1246],
        [11.1795,  9.0303]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################


6개의 다른 명령어로 출력하였는데 
첫번째 randint는 low와 high사이의 랜덤한 값을 (1,2)크기 만큼 출력하는 것이다. 
두번째 rand는 0부터 1사이의 랜덤한 값을 (1,3)크기만큼 출력하였다. 
세번째 randn은 rand를 정규분포의 형태를 갖도록 하고 (1,3)크기만큼 출력하였다. 
네번쨰 normal은 평균과 표준편차, 크기를 입력받아 그에 맞는 정규분포에서 (3,2)크기만큼 출력하였다. 
다섯번쨰 linspace는 시작과 끝 사이의 1차원 텐서를 반환하고 단계를 기준으로 동일한 간격을 갖도록 출력하였다. 
여섯번째 arange는 시작을 포함, 끝을 포함하지 않는 1차원 텐서를 반환하고 동일한 단계간격을 갖도록 출력하였다. 

In [8]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


분명 random을 통해 임의의 값을 출력하였는데 위와 아래는 같은 값이다. 이는 같은 seed를 사용해 고정된 값을 호출했기 때문이다. 이를 이용해 임의의 값을 다시 재현할 수 있다. 이 기능이 없으면 임의의 값을 통해 얻은 특정 결과를 다시 확인해야할 일이 있을 때 어려움을 겪을 수 있기에 필요하다는 생각이 들었다. 

5. e_tensor_type_conversion.py 실행결과

In [9]:
import torch

a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


e에서는 tensor의 타입 형변환에 대해 연습할 수 있었다. (크기), dtype = ??의 형태로 작성하면 tensor의 타입을 원하는 것으로 변경되는 것을 볼 수 있었다. 또한 다른 언어들과 마찬가지로 상위 타입에서 하위 타입으로 형변환될 땐 표현할 수 없는 값은 버림처리한다는 것도 확인했다. 

6. f_tensor_operations.py 실행결과

In [10]:
import torch

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


f에서는 tensor의 사칙연산 함수에 대해 연습할 수 있었다. 덧셈, 뺄셈, 곱셈, 나눗셈을 진행했고, 제공하는 함수와 + - * /연산자를 이용한 연산 모두 정상적으로 작동함을 확인할 수 있었고, 둘의 계산 결과가 같음도 보일 수 있었다. 

7. g_tensor_operations_mm.py 실행결과

In [11]:
import torch

t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())


tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


g에서는 dot - 점곱셈, mm - 행렬곱셈, bmm-일괄행렬곱셈 연산을 수행했다. 행렬 곱셈은 기존 대학수학에서 여러차례 경험해봤기 때문에 바로 이해할 수 있었지만 점곱셈이라는 개념을 제대로 이해할 수 없었다. 

8. h_tensor_operations_matmul.py 실행결과

In [12]:
import torch

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


h에서는 tensor간의 행렬곱셈을 matmull을 사용해 수행했다. g에서의 행렬곱셈과 다른 점은 없지만 size만이 출력되는 것이 차이점이었던 것 같다. 

9. i_tensor_broadcasting.py 실행결과

In [13]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2


1에서는 t2가 t1의 모든 항목에 곱해지는 모습을 확인했고, 2에서는 t4가 t3의 모든 항목과 같은 형태를 가지기 때문에 모든 항목과 연산을 수행하는 모습을 확인했다. 

In [14]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)


def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4


3과 4를 통해 print에서 수행되는 연산 역시 add,sub,mul,div와 똑같이 수행되는 것과 randn의 size가 정상적으로 출력되는 것을 확인할 수 있었지만 normalize가 어떤 역할을 하는지는 잘 모르겠다. 

In [15]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6


5에서는 다양한 형태의 덧셈이 어떻게 되는지 좀 더 다양한 경우를 통해 확인할 수 있었다.
6에서는 shape에 rand가 곱해져도 shape에는 변화가 없음을 확인했다. 

In [16]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


7에서는 두 tensor의 dimension크기를 뒤에서 앞으로 비교하는 것이 말로는 이해하기 어려웠는데 어떻게 진행되는건지 파악할 수 있었다. 
8에서는 pow의 형태와 사용방법을 익혔다. 

10. j_tensor_indexing_slicing.py 실행결과

In [17]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


j에서는 print에서 index를 이용해 일부만 출력하는 것에대해 연습할 수 있었다. 다만 0부터 size-1로 index가 적용된다는 것을 염두에 둬야할 것 같다. :을 이용해 범위를 지정하는 것 역시 쉽게 익숙해질 수 있었지만, 기억해둬야겠다고 생각했다. 

11. k_tensor_reshaping.py 실행결과

In [18]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1


1에서는 view와 reshape를 사용했다. view는 tensor를 지정한 범위만큼만 볼 수 있고, reshape는 값의 수정없이 tensor의 형태만 바뀐다. 

In [19]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3


2와 3에서는 squeeze와 unsqueeze를 사용했다. squeeze는 차원을 한단계 낮추는 것, unsqueeze는 차원을 한단계 높여주는 것이란 말을 듣고는 잘 이해가 안됬는데 출력된 결과를 보고 대괄호의 변화를 자세히 살펴보니 이해할 수 있었다. 

In [20]:

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


이번엔 flatten과 permute, transpose를 사용했다. flatten은 말 그대로 tensor의 shape를  납작하게 만들어주는 reshape의 일종이었고 원한다면 dim도 지정해줄 수 있었다. permute는 shape를 가로세로 뒤집어주는 reshape였고, transpose도 이와 유사한 형태를 가지는데 표현적인 차이를 제외하고 기능적인 차이가 있는지 궁금했다.  

12. l_tensor_concat.py 실행결과

In [21]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3


1,2,3은 텐서를 병합하는 cat함수를 dim을 여러차례 바꿔가며 실행한 결과이다. dim에 해당하는 숫자를 합치는 느낌으로 이해하니 쉽게 구분할 수 있었다. 

In [22]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


4,5,6은 마찬가지로 cat을 사용하는 코드였는데 한 차원 큰 텐서를 합쳤다. 처음엔 두 코드의 출력값이 크게 다르지 않아 차이점을 찾는게 어려웠는데 size와 tensor shape를 대조해가며 보니 일부로 비슷한 출력을 갖도록 텐서를 조정한게 아닐까하는 생각이 들었다. 

13. m_tensor_stacking.py 실행 결과

In [23]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True


torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


텐서를 stack함수를 사용해 만든 텐서와 unsqueeze후 cat을 통해 다시 합친 텐서를 비교하는 내용의 코드를 실행했는데 이는 모두 같게 나왔다. 어떤 방식을 사용했든지 간에 equal은 텐서의 shape만을 비교한다는 것을 알 수 있었고 이미 익힌 squeeze와 cat을 통해 stack의 작동방식을 보다 쉽게 이해할 수 있었던 것 같다. 

14. n_tensor_vstack_hstack.py 실행결과

In [24]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


vstack과 hstack을 사용했는데 stack과 유사한 기능을 하지만 v는 아마 vertical의 v인지 세로로 스택을 쌓았고 h는 horizontal인지 가로로 스택을 쌓았다. 이 역시 위의 예시들과 마찬가지로 사용한 예시 size가 동일하고, 대괄호나 ,등의 약간의 차이만 보여 구분하는데 어려움을 겪었다. 지금은 미리 어떤 것이 사용되었는지 알고 결과물을 확인해 그나마 어떻게든 구분할 수 있었지만, 둘의 결과만 보고 어떤 것이 사용했는지 알아내려면 좀 더 이에 대해 익숙해져야겠다고 생각했다. 

숙제 후기

jupyter Notebook을 사용해본 것은 이번이 처음이었는데 생각보다 익숙해지기 어려웠다. 웹에서 하다가 jupyter Notebook이 열려야만 웹이 작동하는 건지 모르고 프로그램을 종료해 저장하지 않은 부분을 날려버렸을 땐 정말 아찔했다. 또 텐서 구조체의 방대한 함수를 일일히 예제를 통해 확인해보니 과제의 분량도 어마어마했다. 
약간 수학 중에서도 기하학에 가까운 이 텐서 구조체가 딥러닝에서 어떻게 활용되는 것인지 앞으로가 조금 궁금하면서도 두렵기도 했다. 딥러닝을 다루기 위해서는 이번 과제에서 연습한 그 무수히 많은 함수들이 필요하다는 뜻일 거 같다는 생각이 들었기 때문이다. 